language: android

sudo: required

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.0.3

    # The SDK version used to compile your project
    - android-27

    # Additional components
    - extra-android-m2repository

before_script:
  # Download Android NDK, OpenCV Android SDK and Eigen 3
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - wget https://github.com/opencv/opencv/releases/download/3.4.1/opencv-3.4.1-android-sdk.zip
  - wget https://bitbucket.org/eigen/eigen/get/3.3.4.zip -O Eigen3.zip

  # Unzip the zip files
  - unzip -q android-ndk-*-linux-x86_64.zip
  - unzip -q opencv-*-android-sdk.zip
  - unzip -q Eigen3.zip

  # Set environmental variables
  - export ANDROID_NDK_HOME=$(pwd)/android-ndk-r16b
  - export OPENCV_ANDROID_SDK=$(pwd)/OpenCV-android-sdk
  - export EIGEN3_DIR=$(dirname $(find $(pwd) -type f -name 'signature_of_eigen3_matrix_library' -print -quit))

script:
  - ./gradlew build

before_deploy:
  # Clean the project
  - ./gradlew clean
  - rm -rf build

  # Remove git files
  - find . -name .git | xargs rm -rf
  - find . -name .gitmodules | xargs rm -rf
  - find . -name .gitignore | xargs rm -rf
  - find . -name .gitattributes | xargs rm -rf

  # Remove zip files
  - rm -f android-ndk-*-linux-x86_64.zip
  - rm -f opencv-*-android-sdk.zip
  - rm -f Eigen3.zip

  # Remove unused directories
  - rm -rf android-ndk-*
  - rm -rf OpenCV-android-sdk/apk
  - rm -rf OpenCV-android-sdk/samples

  # Hardcode paths to OpenCV and Eigen3
  - EIGEN3_DIR_NAME=$(basename $EIGEN3_DIR)
  - sed -i app/src/main/cpp/Android.mk -e "s/\$(OPENCV_ANDROID_SDK)/\$(LOCAL_PATH)\/..\/..\/..\/..\/OpenCV-android-sdk/"
  - sed -i settings.gradle -e "s/System.getenv('OPENCV_ANDROID_SDK')/'OpenCV-android-sdk'/"
  - sed -i app/src/main/cpp/Android.mk -e "s/\$(EIGEN3_DIR)/\$(LOCAL_PATH)\/..\/..\/..\/..\/$EIGEN3_DIR_NAME/"

  # Zip the directory
  - cd ../
  - mv FaceRecognitionApp "FaceRecognitionApp-$TRAVIS_TAG"
  - zip -rq "FaceRecognitionApp-$TRAVIS_TAG.zip" "FaceRecognitionApp-$TRAVIS_TAG"
  - APP_ZIP=$(pwd)/"FaceRecognitionApp-$TRAVIS_TAG.zip"

deploy:
  provider: releases
  api_key:
    secure: AS5TYcwjqZes1JKqQTryPifgijqJd8H2lowmOWDPSwc17DYFWrU58TR2yn1KYFMQ0dzBse7q6W4Pa43UFl0vsNQaOzKiEg93NSZowXZx+uOF2nlfayFFxfGqVaKKyNpsV1Tmp+Q0eUK5XxBxJ5aSBgJ0II0lyjDaeNJ86x8mvxWoznRy4Ra9COiKnO5kRjwIoCbQFZcf9We4TuSzVnnAIKMeX1rYyczx099FWayIVgT1WSZYZ5r60iU2MZbpkP1/MAcZEOy9OhdQQYm4RYaVq2gmIgGqRKnQ6i9hJXHyNH/u8S3YOrK9SA6XSLN66KCnK4Sk/LtIIrw7ZVkgyHrgmp+hA4JiBuAGIlvDoMJHg8P1EWj2JeVh63NXJSFYvHgRqNpan+9Z+QISi+cAeejbQEumTLA3QJgdgCN22n6hgLWtPWLe4MDVZmWfhIZNZjQZC0C9w3Zi0fwJlf2fC2lQ2tthUBdX3CsM4Ct2Ev2Y+gWo0A4ykcgm0irv81BX6Pd9WAGNnT35+68xv5IU+K0RNT8XJD1aekVY7n7Z3I8f8n99OnFwP6k2T+4rseaY2pQT4aAmsLRKWtm5oKhPFW5hxjzd8REunohUZz81QdvDdCB6wm/knqIqy+A4kzoKkF2CrQxWGM4/hD0/Cnk5oGZSNNJYbfsb4SpBWwl7NiG1GzM=
  file: "$APP_ZIP"
  skip_cleanup: true
  on:
    tags: true
